## DataFrame

In [66]:
import numpy as np
import pandas as pd

In [67]:
data = np.random.randn(4,3)
data

array([[-0.46116544, -0.76921826,  0.02539098],
       [-0.30788387, -0.08218852,  0.60982235],
       [-1.50793913,  0.25898169, -1.34810349],
       [-1.84914921, -0.92272502,  0.57240469]])

In [68]:
# Series ile tek boyutlu data dışında data tutamayız. Tek boyuttan büyükler için DataFrame kullanırız.
data_frame = pd.DataFrame(data)
data_frame

          0         1         2
0 -0.461165 -0.769218  0.025391
1 -0.307884 -0.082189  0.609822
2 -1.507939  0.258982 -1.348103
3 -1.849149 -0.922725  0.572405

In [69]:
type(data_frame)

pandas.DataFrame

In [70]:
print(data_frame[0])
print(type(data_frame[0]))

0   -0.461165
1   -0.307884
2   -1.507939
3   -1.849149
Name: 0, dtype: float64
<class 'pandas.Series'>

In [71]:
new_df = pd.DataFrame(data,index=["Kaan","Eren","Yavuz","Ayşe"],columns=["Salary","Age","Seniority"])
new_df

         Salary       Age  Seniority
Kaan  -0.461165 -0.769218   0.025391
Eren  -0.307884 -0.082189   0.609822
Yavuz -1.507939  0.258982  -1.348103
Ayşe  -1.849149 -0.922725   0.572405

In [72]:
new_df["Age"]

Kaan    -0.769218
Eren    -0.082189
Yavuz    0.258982
Ayşe    -0.922725
Name: Age, dtype: float64

In [73]:
new_df[["Age","Salary"]]

            Age    Salary
Kaan  -0.769218 -0.461165
Eren  -0.082189 -0.307884
Yavuz  0.258982 -1.507939
Ayşe  -0.922725 -1.849149

In [74]:
new_df.loc["Kaan"] # rowlar için .loc kullanırız.

Salary      -0.461165
Age         -0.769218
Seniority    0.025391
Name: Kaan, dtype: float64

In [75]:
new_df.iloc[0] # iloc -> index location

Salary      -0.461165
Age         -0.769218
Seniority    0.025391
Name: Kaan, dtype: float64

In [76]:
new_df.iloc[:,1] # : -> bütün rowları seçer daha sonrada hangi column'ı istersek onu seçeriz.

Kaan    -0.769218
Eren    -0.082189
Yavuz    0.258982
Ayşe    -0.922725
Name: Age, dtype: float64

In [77]:
new_df["Extra"] = 10 # Hepsine Extra Column'ı ekler ve değerini 10 yapar.

In [78]:
new_df

         Salary       Age  Seniority  Extra
Kaan  -0.461165 -0.769218   0.025391     10
Eren  -0.307884 -0.082189   0.609822     10
Yavuz -1.507939  0.258982  -1.348103     10
Ayşe  -1.849149 -0.922725   0.572405     10

In [79]:
new_df.drop("Extra",axis=1) # Extra column'ını drop ettik, axis değeri default = 0'dır.
#fakat başka bir değişkene atamazsak new_df hala aynı

         Salary       Age  Seniority
Kaan  -0.461165 -0.769218   0.025391
Eren  -0.307884 -0.082189   0.609822
Yavuz -1.507939  0.258982  -1.348103
Ayşe  -1.849149 -0.922725   0.572405

In [80]:
new_df

         Salary       Age  Seniority  Extra
Kaan  -0.461165 -0.769218   0.025391     10
Eren  -0.307884 -0.082189   0.609822     10
Yavuz -1.507939  0.258982  -1.348103     10
Ayşe  -1.849149 -0.922725   0.572405     10

In [81]:
new_df.drop("Extra",axis=1,inplace=True) # inplace=True yaparak kalıcı olarak droplarız.
new_df

         Salary       Age  Seniority
Kaan  -0.461165 -0.769218   0.025391
Eren  -0.307884 -0.082189   0.609822
Yavuz -1.507939  0.258982  -1.348103
Ayşe  -1.849149 -0.922725   0.572405

In [82]:
new_df.loc["Kaan"]

Salary      -0.461165
Age         -0.769218
Seniority    0.025391
Name: Kaan, dtype: float64

In [83]:
new_df.loc["Kaan"]["Salary"]

np.float64(-0.4611654360442592)

In [84]:
new_df.loc["Kaan","Salary"] # Yukarıdaki işlemin aynısıdır.

np.float64(-0.4611654360442592)

In [85]:
new_df.loc["Kaan","Salary"] = 100 # İlk şekildeki gibi yaparsak değiştirmiyor.
new_df

           Salary       Age  Seniority
Kaan   100.000000 -0.769218   0.025391
Eren    -0.307884 -0.082189   0.609822
Yavuz   -1.507939  0.258982  -1.348103
Ayşe    -1.849149 -0.922725   0.572405

In [86]:
new_df > 0

       Salary    Age  Seniority
Kaan     True  False       True
Eren    False  False       True
Yavuz   False   True      False
Ayşe    False  False       True

In [87]:
new_df[new_df > 0]

       Salary       Age  Seniority
Kaan    100.0       NaN   0.025391
Eren      NaN       NaN   0.609822
Yavuz     NaN  0.258982        NaN
Ayşe      NaN       NaN   0.572405

In [88]:
new_df[new_df["Salary"] > 1] # Salary'si 1'den büyük olanlar.

      Salary       Age  Seniority
Kaan   100.0 -0.769218   0.025391

In [89]:
new_df.reset_index() # indexi ayrı bir column olarak açar ve veriyi indexler

   index      Salary       Age  Seniority
0   Kaan  100.000000 -0.769218   0.025391
1   Eren   -0.307884 -0.082189   0.609822
2  Yavuz   -1.507939  0.258982  -1.348103
3   Ayşe   -1.849149 -0.922725   0.572405

In [90]:
reset_frame = new_df.reset_index()
# reset_frame.loc["Kaan"] Çalısmaz
reset_frame.loc[0]

index            Kaan
Salary          100.0
Age         -0.769218
Seniority    0.025391
Name: 0, dtype: object

In [91]:
new_indices = ["K","E","Y","A"]
new_df["NewIndex"] = new_indices
new_df

           Salary       Age  Seniority NewIndex
Kaan   100.000000 -0.769218   0.025391        K
Eren    -0.307884 -0.082189   0.609822        E
Yavuz   -1.507939  0.258982  -1.348103        Y
Ayşe    -1.849149 -0.922725   0.572405        A

In [92]:
new_df.set_index("NewIndex",inplace=True) # Yeni Index Column'ımız artık NewIndex
new_df.loc["K"]

Salary       100.000000
Age           -0.769218
Seniority      0.025391
Name: K, dtype: float64

In [93]:
new_df

              Salary       Age  Seniority
NewIndex
K         100.000000 -0.769218   0.025391
E          -0.307884 -0.082189   0.609822
Y          -1.507939  0.258982  -1.348103
A          -1.849149 -0.922725   0.572405

### multi-index

In [94]:
first_index = ["Simpson","Simpson","Simpson","South Park","South Park","South Park"]
inner_index = ["Homer","Bart","Marge","Cartman","Kenny","Kyle"]
zipped_index = list(zip(first_index,inner_index))
zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [95]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)
zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [98]:
sample_values = np.ones((6,2))
big_df = pd.DataFrame(sample_values, index = zipped_index, columns = ["Age","Salary"])
big_df

                    Age  Salary
Simpson    Homer    1.0     1.0
           Bart     1.0     1.0
           Marge    1.0     1.0
South Park Cartman  1.0     1.0
           Kenny    1.0     1.0
           Kyle     1.0     1.0

In [99]:
big_df["Age"]

Simpson     Homer      1.0
            Bart       1.0
            Marge      1.0
South Park  Cartman    1.0
            Kenny      1.0
            Kyle       1.0
Name: Age, dtype: float64

In [ ]:
#big_df.loc["Homer"] # KeyError
big_df.loc["Simpson"].loc["Homer"] # Dıştan içe doğru gider loclar.

Age       1.0
Salary    1.0
Name: Homer, dtype: float64